const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://nextsec.vercel.app";

function baseTemplate(content: string): string {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>XyberSec Academy</title></head><body style="margin:0;padding:0;background:#050a14;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#050a14;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;"><tr><td style="padding:0 0 32px 0;text-align:center;"><table cellpadding="0" cellspacing="0" style="display:inline-block;"><tr><td style="background:#0d1526;border:1px solid rgba(34,211,238,0.3);border-radius:12px;padding:12px 20px;"><span style="color:#22d3ee;font-size:18px;font-weight:700;letter-spacing:-0.5px;">🛡️ XyberSec Academy</span></td></tr></table></td></tr><tr><td style="background:#0d1526;border:1px solid rgba(34,211,238,0.15);border-radius:16px;padding:40px 32px;">${content}</td></tr><tr><td style="padding:24px 0 0 0;text-align:center;"><p style="color:#4a5568;font-size:12px;margin:0 0 8px 0;">XyberSec Academy · Ethiopia's #1 Cybersecurity Platform</p><p style="margin:0;"><a href="${APP_URL}" style="color:#22d3ee;font-size:12px;text-decoration:none;">Visit XyberSec Academy</a>&nbsp;·&nbsp;<a href="${APP_URL}/dashboard" style="color:#22d3ee;font-size:12px;text-decoration:none;">Dashboard</a></p><p style="color:#4a5568;font-size:11px;text-align:center;margin:8px 0 0 0;"><a href="${APP_URL}/settings/notifications" style="color:#4a5568;text-decoration:none;">Unsubscribe from emails</a></p></td></tr></table></td></tr></table></body></html>`;
}

function ctaButton(text: string, url: string): string { return `<table cellpadding="0" cellspacing="0" style="margin:24px 0;"><tr><td style="background:#22d3ee;border-radius:12px;"><a href="${url}" style="display:block;padding:14px 28px;color:#050a14;font-weight:700;font-size:15px;text-decoration:none;text-align:center;">${text}</a></td></tr></table>`; }
function statBox(icon: string, value: string, label: string): string { return `<td style="text-align:center;background:#0a1628;border:1px solid rgba(34,211,238,0.1);border-radius:10px;padding:16px 12px;width:30%;"><div style="font-size:24px;margin-bottom:4px;">${icon}</div><div style="color:#22d3ee;font-size:20px;font-weight:700;margin-bottom:2px;">${value}</div><div style="color:#718096;font-size:12px;">${label}</div></td>`; }

export function welcomeEmailTemplate({ username, firstName, courseSlug, cpBalance }: { username: string; firstName: string; courseTitle?: string; courseSlug?: string; cpBalance: number; }) { const subject = `Welcome to XyberSec, @${username}! 🛡️`; const html = baseTemplate(`<h1 style="color:#ffffff;font-size:28px;font-weight:700;margin:0 0 8px 0;">Welcome, @${username}! 👋</h1><p style="color:#22d3ee;font-size:14px;margin:0 0 24px 0;">🇪🇹 You've joined Ethiopia's #1 Cybersecurity Academy</p><p style="color:#a0aec0;font-size:15px;line-height:1.6;margin:0 0 24px 0;">Hi ${firstName}, your XyberSec account is ready.</p><table width="100%" cellpadding="6" cellspacing="0" style="margin:0 0 24px 0;"><tr>${statBox("⚡", `${cpBalance} CP`, "Welcome Bonus")}<td width="5%"></td>${statBox("🆓", "Free", "First Module")}<td width="5%"></td>${statBox("🤖", "AI", "Tutor Included")}</tr></table>${courseSlug ? ctaButton("Start Your First Lesson →", `${APP_URL}/courses/${courseSlug}`) : ctaButton("Browse Courses →", `${APP_URL}/courses`)}`); return { subject, html }; }
export function moduleCompleteEmailTemplate({ username, moduleName, courseName, courseSlug, xpEarned, totalXP }: any) { const subject = `Module Complete! +${xpEarned} XP earned 🎯`; const html = baseTemplate(`<h1 style="color:#fff;">Module Complete!</h1><p style="color:#22d3ee;">Keep going, @${username}</p><p style="color:#a0aec0;">${moduleName} from ${courseName}</p><table width="100%" cellpadding="6" cellspacing="0"><tr>${statBox("⚡", `+${xpEarned}`, "XP Earned")}<td width="5%"></td>${statBox("🏆", `${totalXP}`, "Total XP")}<td width="5%"></td>${statBox("🔥", "Keep", "Streak Alive!")}</tr></table>${ctaButton("Continue Learning →", `${APP_URL}/courses/${courseSlug}`)}`); return { subject, html }; }
export function courseCompleteEmailTemplate({ username, courseName, courseSlug, totalXP, totalLessons }: any) { const subject = `🎓 You completed ${courseName}! Claim your certificate`; const html = baseTemplate(`<h1 style="color:#fff;">Course Complete, @${username}!</h1><table width="100%" cellpadding="6" cellspacing="0"><tr>${statBox("📚", `${totalLessons}`, "Lessons Done")}<td width="5%"></td>${statBox("⚡", `${totalXP}`, "Total XP")}<td width="5%"></td>${statBox("🎓", "Ready", "Certificate")}</tr></table>${ctaButton("Claim Your Certificate 🎓", `${APP_URL}/courses/${courseSlug}`)}`); return { subject, html }; }
export function certificateIssuedEmailTemplate({ username, courseName, certCode, issuedDate }: any) { const subject = `Your XyberSec Certificate is ready! 🎓`; const html = baseTemplate(`<h1 style="color:#fff;">Certificate Issued!</h1><p style="color:#22d3ee;">Congratulations, @${username}</p><p style="color:#a0aec0;">${courseName} · ${certCode} · ${issuedDate}</p>${ctaButton("View & Download Certificate →", `${APP_URL}/certificate/${certCode}`)}`); return { subject, html }; }
export function cpPurchaseEmailTemplate({ username, cpAmount, newBalance, packageName, amountPaid }: any) { const subject = `✅ ${cpAmount} CyberPoints added to your account`; const html = baseTemplate(`<h1 style="color:#fff;">Payment Confirmed!</h1><p style="color:#22d3ee;">@${username}</p><p style="color:#a0aec0;">${packageName} · ETB ${amountPaid}</p><table width="100%" cellpadding="6" cellspacing="0"><tr>${statBox("⚡", `${cpAmount}`, "CP Added")}<td width="5%"></td>${statBox("💳", `${newBalance}`, "New Balance")}<td width="5%"></td>${statBox("♾️", "Never", "Expires")}</tr></table>${ctaButton("Start Unlocking Modules →", `${APP_URL}/courses`)}`); return { subject, html }; }
export function streakReminderEmailTemplate({ username, currentStreak, lastCourseName, lastCourseSlug, hoursLeft }: any) { const subject = currentStreak >= 7 ? `🔥 Don't break your ${currentStreak}-day streak, @${username}!` : currentStreak >= 3 ? `⚠️ Your ${currentStreak}-day streak is at risk!` : `📚 Time to learn something new today!`; const html = baseTemplate(`<h1 style="color:#fff;">Don't break your streak!</h1><p style="color:#a0aec0;">Hey @${username}</p><p style="color:#a0aec0;">${hoursLeft} hours left</p>${lastCourseSlug ? ctaButton("Continue Learning →", `${APP_URL}/courses/${lastCourseSlug}`) : ctaButton("Start Learning Today →", `${APP_URL}/courses`)}<p style="color:#718096;">${lastCourseName ?? ""}</p>`); return { subject, html }; }
