"use server";

import { prisma } from "@/lib/prisma";
import { sendEmail, getUserEmail } from "@/lib/email";
import { welcomeEmailTemplate, moduleCompleteEmailTemplate, courseCompleteEmailTemplate, certificateIssuedEmailTemplate, cpPurchaseEmailTemplate } from "@/lib/email-templates";

async function canSend(clerkUserId: string) {
  const profile = await prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { emailNotifications: true } });
  return profile?.emailNotifications !== false;
}

export async function sendWelcomeEmail(clerkUserId: string) { try { if (!(await canSend(clerkUserId))) return; const [email, profile] = await Promise.all([getUserEmail(clerkUserId), prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { username: true, cpBalance: true } })]); if (!email || !profile?.username) return; const { createClient } = await import("next-sanity"); const client = createClient({ projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!, dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!, apiVersion: "2024-01-01", useCdn: false }); const course = await client.fetch(`*[_type == "course" && tier == "free"] | order(_createdAt asc) [0] { title, "slug": slug.current }`); const { subject, html } = welcomeEmailTemplate({ username: profile.username, firstName: profile.username, courseTitle: course?.title, courseSlug: course?.slug, cpBalance: profile.cpBalance ?? 50 }); await sendEmail({ to: email, subject, html }); } catch (err) { console.error("Welcome email failed:", err); } }
export async function sendModuleCompleteEmail(clerkUserId: string, moduleName: string, courseId: string, xpEarned: number) { try { if (!(await canSend(clerkUserId))) return; const [email, profile] = await Promise.all([getUserEmail(clerkUserId), prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { username: true, xpPoints: true } })]); if (!email || !profile?.username) return; const { createClient } = await import("next-sanity"); const client = createClient({ projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!, dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!, apiVersion: "2024-01-01", useCdn: false }); const course = await client.fetch(`*[_type == "course" && _id == $courseId][0] { title, "slug": slug.current }`, { courseId }); const { subject, html } = moduleCompleteEmailTemplate({ username: profile.username, moduleName, courseName: course?.title ?? "the course", courseSlug: course?.slug ?? "", xpEarned, totalXP: profile.xpPoints ?? 0 }); await sendEmail({ to: email, subject, html }); } catch (err) { console.error("Module complete email failed:", err); } }
export async function sendCourseCompleteEmail(clerkUserId: string, courseId: string, totalLessons: number) { try { if (!(await canSend(clerkUserId))) return; const [email, profile] = await Promise.all([getUserEmail(clerkUserId), prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { username: true, xpPoints: true } })]); if (!email || !profile?.username) return; const { createClient } = await import("next-sanity"); const client = createClient({ projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!, dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!, apiVersion: "2024-01-01", useCdn: false }); const course = await client.fetch(`*[_type == "course" && _id == $courseId][0] { title, "slug": slug.current }`, { courseId }); const { subject, html } = courseCompleteEmailTemplate({ username: profile.username, courseName: course?.title ?? "the course", courseSlug: course?.slug ?? "", totalXP: profile.xpPoints ?? 0, totalLessons }); await sendEmail({ to: email, subject, html }); } catch (err) { console.error("Course complete email failed:", err); } }
export async function sendCertificateIssuedEmail(clerkUserId: string, certCode: string, courseId: string) { try { if (!(await canSend(clerkUserId))) return; const [email, profile] = await Promise.all([getUserEmail(clerkUserId), prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { username: true } })]); if (!email || !profile?.username) return; const { createClient } = await import("next-sanity"); const client = createClient({ projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!, dataset: process.env.NEXT_PUBLIC_SANITY_DATASET!, apiVersion: "2024-01-01", useCdn: false }); const course = await client.fetch(`*[_type == "course" && _id == $courseId][0] { title }`, { courseId }); const { subject, html } = certificateIssuedEmailTemplate({ username: profile.username, courseName: course?.title ?? "the course", certCode, issuedDate: new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) }); await sendEmail({ to: email, subject, html }); } catch (err) { console.error("Certificate email failed:", err); } }
export async function sendCPPurchaseEmail(clerkUserId: string, cpAmount: number, packageName: string, amountPaid: number) { try { if (!(await canSend(clerkUserId))) return; const [email, profile] = await Promise.all([getUserEmail(clerkUserId), prisma.userProfile.findUnique({ where: { clerkId: clerkUserId }, select: { username: true, cpBalance: true } })]); if (!email || !profile?.username) return; const { subject, html } = cpPurchaseEmailTemplate({ username: profile.username, cpAmount, newBalance: profile.cpBalance ?? cpAmount, packageName, amountPaid }); await sendEmail({ to: email, subject, html }); } catch (err) { console.error("CP purchase email failed:", err); } }
